Added support for eigenstrain external field.
oofem/oofem pull request #156
Opened 2024-09-15 07:57 UTC by vit-smilauer

2024-10-31 14:04 UTC, bpatzak commented
Hi Vit,
sorry for delay on my side. I have two comments:
- the modification of Element :: giveMaterial() method perhaps fixes specific problem, but I would welcome more generic fix. This method (or as it is defined) is conceptually wrong, as elements can have multiple materials (when using layered cross section, for example). So there is no single material for element. The possible solution would be to add integration point as parameter and this could be used to correctly resolve material (ass CrossSection::giveMaterial does).
- Can you merge it to devel branch ? I would prefer individual pull requests to go to devel branch, test everything and finally make one merge of devel to master.

2025-02-28 19:05 UTC, bpatzak commented on tests/sm/deepbeamfe2_01.in.rve
Please double check if the files can be removed, I am sure some are needed. For example, this file is needed for deepbeamFE_01.in file.

2025-02-28 19:06 UTC, bpatzak requested changes
Please double check that files can be deleted.
For example, deepbeamfe2_01.in.rve is needed by tests/sm/deepbeamFE2_01.in !!!

2025-03-14 10:23 UTC, vit-smilauer commented
I will do the pull request through devel version.

2025-03-14 10:23 UTC, closed without merging